package protocol

import "errors"

var (
	ErrInvalidIdentifier      = errors.New("invalid identifier")
	ErrInvalidPlanID          = errors.New("invalid plan_id")
	ErrInvalidJSON            = errors.New("invalid json")
	ErrUnknownField           = errors.New("unknown json field")
	ErrDuplicateField         = errors.New("duplicate json field")
	ErrMissingField           = errors.New("missing json field")
	ErrTrailingJSON           = errors.New("trailing json")
	ErrInvalidTimestamp       = errors.New("invalid timestamp")
	ErrInvalidToken           = errors.New("invalid token")
	ErrInvalidSignature       = errors.New("invalid signature")
	ErrExpiredToken           = errors.New("expired token")
	ErrReplayWindow           = errors.New("signature timestamp outside replay window")
	ErrInvalidPairingRoot     = errors.New("invalid pairing root")
	ErrInvalidURL             = errors.New("invalid url")
	ErrInvalidEventStatus     = errors.New("incompatible event_type and status")
	ErrInvalidStatus          = errors.New("invalid status")
	ErrInvalidEventType       = errors.New("invalid event_type")
	ErrIdentityField          = errors.New("consumer identity fields are not permitted")
	ErrUnsupportedVersion     = errors.New("unsupported protocol version")
	ErrInvalidProtocol        = errors.New("invalid protocol")
	ErrUnorderedPeriod        = errors.New("period end must be after period start")
	ErrCancelFlagMismatch     = errors.New("cancel_at_period_end does not match status")
	ErrBodyTooLarge           = errors.New("request body too large")
	ErrCheckoutConflict       = errors.New("checkout binding conflict")
	ErrCheckoutTerminal       = errors.New("checkout is terminal and cannot be reused")
	ErrUnknownPlan            = errors.New("unknown plan_id")
	ErrNotFound               = errors.New("not found")
	ErrStaleFence             = errors.New("stale fencing token")
	ErrProviderManaged        = errors.New("provider manages this operation")
	ErrAutomaticChargeBlocked = errors.New("automatic charging is blocked")
	ErrFailClosed             = errors.New("request failed closed")
)
